### ISSUE TITLE
Deprecation notice with PHP 8.1

### ISSUE THREAD

**Issue by sebastianbergmann** [justinrainbow/json-schema#668] opened 2021-07-20 07:54 UTC
From https://github.com/sebastianbergmann/phpunit/runs/3111696987:

```
Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated
in phar:///home/runner/work/phpunit/phpunit/tools/composer/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48
```

**Comment by bighappyface** [comment] 2021-07-20 10:58
Always fun to get an issue from @sebastianbergmann 😊

**Comment by Seldaek** [comment] 2021-07-21 13:30
Duplicate of https://github.com/justinrainbow/json-schema/issues/656

**Closed by Seldaek** 2021-07-21 13:30 UTC

**Comment by jmester13** [comment] 2024-04-30 20:56
Hello All, 

In an effort to not create a new issue with no connection back to how I got here I'm responding to this closed but unlocked issue. 

I'm running 

php 8.2.17
composer 2.7.2
on Azure App Service on Linux. 

I'm attempting to deploy after a composer update / install and receiving the following deprecation messages 

`
Deprecation Notice: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in phar:///tmp/oryx/platforms/php-composer/2.0.8/composer.phar/vendor/justinrainbow/json-schema/src/JsonSchema/Constraints/Constraint.php:48\n
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///tmp/oryx/platforms/php-composer/2.0.8/composer.phar/src/Composer/Repository/ArrayRepository.php:277\n
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///tmp/oryx/platforms/php-composer/2.0.8/composer.phar/src/Composer/Repository/ArrayRepository.php:277\n
Deprecation Notice: Return type of Composer\Repository\ArrayRepository::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///tmp/oryx/platforms/php-composer/2.0.8/composer.phar/src/Composer/Repository/ArrayRepository.php:277\n
Deprecation Notice: Return type of Symfony\Component\Finder\Finder::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///tmp/oryx/platforms/php-composer/2.0.8/composer.phar/vendor/symfony/finder/Finder.php:675\n
Deprecation Notice: Return type of Symfony\Component\Finder\Finder::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///tmp/oryx/platforms/php-composer/2.0.8/composer.phar/vendor/symfony/finder/Finder.php:732\n
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FilterIterator::rewind() should either be compatible with FilterIterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///tmp/oryx/platforms/php-composer/2.0.8/composer.phar/vendor/symfony/finder/Iterator/FilterIterator.php:30\n
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\FileTypeFilterIterator::accept() should either be compatible with FilterIterator::accept(): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///tmp/oryx/platforms/php-composer/2.0.8/composer.phar/vendor/symfony/finder/Iterator/FileTypeFilterIterator.php:42\n
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::getChildren() should either be compatible with RecursiveDirectoryIterator::getChildren(): RecursiveDirectoryIterator, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///tmp/oryx/platforms/php-composer/2.0.8/composer.phar/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php:85\n
Deprecation Notice: Return type of Symfony\Component\Finder\Iterator\RecursiveDirectoryIterator::rewind() 
should either be compatible with FilesystemIterator::rewind(): void, or the #[\R`

I've tried the standard nuking of vendor, composer.lock, and my Drupal core and modules files. 

I'm new to Azure, but experienced with Drupal and had the site up and running until earlier today. 

I appreciate and insight and will keep you posted if I find a resolution. 

Cheers
