### ISSUE TITLE
RefResolfer returns null schema

### ISSUE THREAD

**Issue by MikeSebastianD** [justinrainbow/json-schema#253] opened 2016-04-15 08:25 UTC
Hi there, i have a little trouble to get the package up and running. my schema seems to be allways null. 

Here is the line in my code: 
```
$refResolver = new JsonSchema\RefResolver(new \JsonSchema\Uri\UriRetriever(), new JsonSchema\Uri\UriResolver());

$schema = $refResolver->resolve(__DIR__ . "\\schema\\stb_jobs_list.json");
var_dump($refResolver);
var_dump($schema);
```
And the dump:
```
object(JsonSchema\RefResolver)#257 (2) {
  ["uriRetriever":protected]=>
  object(JsonSchema\Uri\UriRetriever)#258 (2) {
    ["uriRetriever":protected]=>
    NULL
    ["schemaCache":"JsonSchema\Uri\UriRetriever":private]=>
    array(0) {
    }
  }
  ["rootSchema":protected]=>
  NULL
}

NULL
```

I'm using the laravel framework to develop a api and need to verify a lot of json data. 

I also get this error message: First parameter must either be an object or the name of an existing class

i validated my test input data and the json schema on the following site http://jsonschemalint.com/ there were no problems in my schema or json data

**Comment by bighappyface** [comment] 2016-04-15 15:28
Perhaps it's the backslashes in your path?

**Comment by jojo1981** [comment] 2016-04-15 16:20
@bighappyface Maybe there is a bug. What if `stb_jobs_list.json` contains invalid JSON.
@MikeSebastianD can you add the content of the file: `stb_jobs_list.json` to this issue? So we can try to reproduce this and conclude if it's a bug or if there is something else wrong.

**Comment by jojo1981** [comment] 2016-04-15 16:21
Maybe this is the same issue: #251

**Comment by bighappyface** [comment] 2016-04-15 17:08
Is `$schema = $refResolver->resolve(_DIR_ . "\schema\stb_jobs_list.json");` valid? I assume this is happening on Windows?

**Comment by MikeSebastianD** [comment] 2016-04-18 09:45
Hi there, 

I have a little update, thanks for the Replys: 

The following line of code is working, if i load the shema by myself: 
(The path is working as well, i tryed it with the absolute path first)

`
   $jsonClean = json_decode($result);

//        $path = "file://C:/dev/repos/backend/STBB/resources/schema/stb_jobs_list.json";
        $path = storage_path('schema/stb_jobs_list.json');
        $schema = json_decode(file_get_contents($path));

        // Validate
        $validator = new JsonSchema\Validator();
        $validator->check($jsonClean, $schema);

        if ($validator->isValid()) {
            echo "The supplied JSON validates against the schema.\n";
        } else {
            echo "JSON does not validate. Violations:\n";
            foreach ($validator->getErrors() as $error) {
                echo sprintf("[%s] %s\n", $error['property'], $error['message']);
            }
        }
`

If I use instead the $refResolver, the schema always returns null. The other problem with the resolver is, that it is a void method and has no return statement. So, if i use the following code:

`   $jsonClean = json_decode($result);

$refResolver = new JsonSchema\RefResolver(new JsonSchema\Uri\UriRetriever(), new JsonSchema\Uri\UriResolver());
$schema = $refResolver->resolve('file://C:/dev/repos/backend/STBB/resources/schema/stb_jobs_list.json');


        // Validate
        $validator = new JsonSchema\Validator();
        $validator->check($jsonClean, $schema);

        if ($validator->isValid()) {
            echo "The supplied JSON validates against the schema.\n";
        } else {
            echo "JSON does not validate. Violations:\n";
            foreach ($validator->getErrors() as $error) {
                echo sprintf("[%s] %s\n", $error['property'], $error['message']);
            }
        }`

it is not working, but if i change the code to the following: 

`  $refResolver = new JsonSchema\RefResolver(new JsonSchema\Uri\UriRetriever(), new JsonSchema\Uri\UriResolver());
        $refResolver->resolve($schema, $path);`

it works.

Is the refResolver function unnecessary/obsolete? Beause if i load the json by myself it is working without problems.

**Comment by jojo1981** [comment] 2016-04-18 20:06
@MikeSebastianD 

- The schema file is valid, so that's **NOT** the problem.
- The `resolve` method of the `RefResolver` is **NOT** a void method. It should return the resolved schema (object) with all replace `$ref` property occurrences if there are any with an object reference to the corresponding schema.
- When you know the used schema has not `$ref` properties than the `RefResolver` can be omitted, but this is **NOT** recommended! 
- The RefResolver may never return `null`. I think this is a bug because I would expect it to throws an exception. I think the problem here is that the injected `UriRetriever` can not resolve the schema file.

Can you try the following code:

    
    $refResolver = new JsonSchema\RefResolver(new \JsonSchema\Uri\UriRetriever(), new JsonSchema\Uri\UriResolver());
    
    $jsonClean = json_decode($result);
    
    // $path = "file://C:/dev/repos/backend/STBB/resources/schema/stb_jobs_list.json";
    $path = storage_path('schema/stb_jobs_list.json');
    
    //$schema = json_decode(file_get_contents($path));
    $schema = refResolver->resolve($path);
    
    // Validate
    $validator = new JsonSchema\Validator();
    $validator->check($jsonClean, $schema);
    
    if ($validator->isValid()) {
        echo "The supplied JSON validates against the schema.\n";
    } else {
        echo "JSON does not validate. Violations:\n";
        foreach ($validator->getErrors() as $error) {
            echo sprintf("[%s] %s\n", $error['property'], $error['message']);
        }
    }

**Comment by MikeSebastianD** [comment] 2016-04-19 11:30
@jojo1981 I think I had imported the wrong RefResolver, Now it's working and the resolve method is not a void method, like you said. (I'm using PhpStorm and the ide said that the method had no return statement, maybe an autoimport wen't wrong.)

**Comment by jojo1981** [comment] 2016-04-19 19:37
@MikeSebastianD Nice! Can you close this issue please? Thanks in advance!

**Comment by jojo1981** [comment] 2016-04-20 19:33
@bighappyface I think this issue can be closed?

**Comment by bighappyface** [comment] 2016-04-20 20:18
@jojo1981 10-4

**Closed by bighappyface** 2016-04-20 20:18 UTC
